Tracker:AddLocations("locations/Adjacent to Catacombs.json")
Tracker:AddLocations("locations/Black Castle Foyer.json")
Tracker:AddLocations("locations/Black Castle Gate.json")
Tracker:AddLocations("locations/Blue Labyrinth 0.json")
Tracker:AddLocations("locations/Blue Labyrinth 1.json")
Tracker:AddLocations("locations/Catacombs.json")
Tracker:AddLocations("locations/Credits Left Side.json")
Tracker:AddLocations("locations/Credits Right Side.json")
Tracker:AddLocations("locations/Dungeon Vault.json")
Tracker:AddLocations("locations/Dungeon0.json")
Tracker:AddLocations("locations/Dungeon1.json")
Tracker:AddLocations("locations/Inside Yellow Castle.json")
Tracker:AddLocations("locations/Northeast of Catacombs.json")
Tracker:AddLocations("locations/Red Maze Vault.json")
Tracker:AddLocations("locations/Red Maze Vault Entrance.json")
Tracker:AddLocations("locations/RedMaze0.json")
Tracker:AddLocations("locations/RedMaze1.json")
Tracker:AddLocations("locations/Slay Grundle.json")
Tracker:AddLocations("locations/Slay Rhindle.json")
Tracker:AddLocations("locations/Slay Yorgle.json")
Tracker:AddLocations("locations/Southeast of Catacombs.json")
Tracker:AddLocations("locations/Southwest of Catacombs.json")
Tracker:AddLocations("locations/White Castle Gate.json")
Tracker:AddLocations("locations/Yellow Castle Gate.json")
Tracker:AddLocations("locations/Overworld.json")
