Tracker:AddLocations("locations/Overworld.json")
Tracker:AddLocations("locations/Town.json")
Tracker:AddLocations("locations/Sewers.json")
Tracker:AddLocations("locations/Petal_Meadows.json")
Tracker:AddLocations("locations/Shhwonk_Fortress.json")
Tracker:AddLocations("locations/Player_Positions.json")